# Generated by Django 3.1.2 on 2020-10-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('prov', models.CharField(max_length=50)),
                ('pob', models.IntegerField()),
                ('g_rec_sol', models.DecimalField(decimal_places=2, max_digits=15)),
                ('g_rec_sol_rec', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProdMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mat')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.prod')),
            ],
        ),
        migrations.CreateModel(
            name='CompRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.localidad')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.prod')),
            ],
        ),
    ]
