# Generated by Django 3.1.2 on 2020-10-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recol', models.DecimalField(decimal_places=2, max_digits=15)),
                ('clasf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('edu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('f_carga', models.DateField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='GIRSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recup', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empleos', models.IntegerField()),
                ('g_rec', models.DecimalField(decimal_places=2, max_digits=15)),
                ('g_girsu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('f_corresp', models.DateField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='GGirsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoleccion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gest_reci', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disp_trat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('f_carga', models.DateField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolecccion', models.IntegerField()),
                ('clas', models.IntegerField()),
                ('educ', models.IntegerField()),
                ('disp', models.IntegerField()),
                ('f_carga', models.DateField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
    ]
