# Generated by Django 3.1.2 on 2020-10-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('MU', 'Municipio'), ('CO', 'Cooperativa'), ('PL', 'Punto Limpio'), ('EM', 'Empresa')], default='', max_length=2),
        ),
    ]
