# Generated by Django 3.1.2 on 2020-10-17 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='EnvP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='StockProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.prod')),
            ],
        ),
        migrations.CreateModel(
            name='StockMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mat')),
            ],
        ),
        migrations.CreateModel(
            name='RecP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp', models.BooleanField(default=False)),
                ('f_recp', models.DateTimeField(auto_now=True)),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.envp')),
            ],
        ),
        migrations.CreateModel(
            name='RecM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp', models.BooleanField(default=False)),
                ('f_recp', models.DateTimeField(auto_now=True)),
                ('ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.entidad')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.envm')),
            ],
        ),
        migrations.CreateModel(
            name='MovSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockprod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockmat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='envp',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockprod'),
        ),
        migrations.AddField(
            model_name='envm',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockmat'),
        ),
    ]
