# Generated by Django 3.1.2 on 2020-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envp',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Tn', 'Toneladas')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movsm',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Tn', 'Toneladas')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movsp',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Tn', 'Toneladas')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmat',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Tn', 'Toneladas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stockprod',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Tn', 'Toneladas')], max_length=2),
        ),
    ]
