# Generated by Django 3.1.2 on 2020-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201026_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='movsm',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('SA', 'Salida')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movsp',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('SA', 'Salida')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
