# Generated by Django 3.1.2 on 2020-10-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
        ('stocks', '0003_auto_20201026_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movsm',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mat'),
        ),
        migrations.AlterField(
            model_name='movsp',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.prod'),
        ),
    ]
