# Generated by Django 3.1.2 on 2020-10-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_auto_20201026_1810'),
        ('stocks', '0004_auto_20201026_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envm',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mat'),
        ),
        migrations.AlterField(
            model_name='envp',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.prod'),
        ),
    ]
